- name: Provision Ubuntu Image
  become: true
  hosts: localhost
  tasks:
  - name: Install Python
    apt:
      name: python3.6
      state: present

  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name: Start NGiNX
    service:
      name: nginx
      state: started

  - name: touch a file
    ansible.builtin.file:
      path: /etc/bilal.txt
      state: touch

