
source "azure-arm" "autogenerated_1" {
  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "18.04-LTS"
  location                          = "East US"
  managed_image_name                = "BilalPackerUbuntuImage"
  managed_image_resource_group_name = "bilal-packer-rg"
  os_type                           = "Linux"
  use_azure_cli_auth                = true
  vm_size                           = "Standard_DS1_v2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    inline = [
      "sudo apt-add-repository --yes --update ppa:ansible/ansible",
      "sudo apt update -y",
      "sudo apt install ansible -y"
    ]
  }

  provisioner "ansible-local" {
      playbook_file = "../../ansible/ubuntu.yml"
    }

  provisioner "shell" {
    inline = ["echo 'This is a text written by packer' > /etc/bilal.txt"]
  }
}
